version: "3.8"

services:
  
  # 2. MongoDB Database Service
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty

    volumes:
      - mongo_data:/data/db

  # 3. Mongo-Express UI Service
  mongo-express:
    image: mongo-express
    ports: 
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/ 

    volumes:
       mongo_data:

    
